### ISSUE TITLE
Not possible to generate mock

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#135]
**Describe the bug**
Command for mock generation fails

**To Reproduce**
1. Create a project with some simple library
```bash
scargo new some03
cd some03
.... create a library
```
- project in the attachment
[mock_gen.zip](https://github.com/Spyro-Soft/scargo/files/11080164/mock_gen.zip)

2. Open project in docker
```bash
scargo docker run
```

3. Generate mock for the library header file
```bash
scargo gen -u src/libs/test_lib/test_lib.h
```

The command finishes with an error and no mock is created
```bash
kmc@37c54307c58c:/workspace$ scargo gen -m src/libs/test_lib/test_lib.h
Traceback (most recent call last):

  File "/usr/local/bin/scargo", line 8, in <module>
    sys.exit(cli())

  File "/usr/local/lib/python3.8/dist-packages/scargo/cli.py", line 303, in gen
    scargo_gen(

  File "/usr/local/lib/python3.8/dist-packages/scargo/commands/gen.py", line 46, in scargo_gen
    if generate_mocks(gen_mock):

  File "/usr/local/lib/python3.8/dist-packages/scargo/jinja/mock_gen.py", line 56, in generate_mocks
    gen_header(dst_header, "class_interface.h.j2", header_data)

  File "/usr/local/lib/python3.8/dist-packages/scargo/jinja/mock_gen.py", line 75, in gen_header
    with path.open("w", encoding="utf-8") as out:

  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,

  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)

FileNotFoundError: [Errno 2] No such file or directory: '/workspace/src/libs/tests/mocks/test_lib.h'

```

**Expected behavior**
Mocks generated and added to the test build

**Additional info**
```
scargo version
scargo version: 1.1.0
```

**Comment by kmc-spyro** [comment]
Checked and the mocks are still not being generated.

BTW - the command in the description is wrong - it shall be the `-m` option used instead (`-u` generates unit test and this one works)

```bash
kmc@c59210fddacf:/workspace$ scargo clean
scargo INFO: Removed /workspace/build
kmc@c59210fddacf:/workspace$ scargo gen -m src/libs/test_lib/test_lib.h
Traceback (most recent call last):

  File "/usr/local/bin/scargo", line 8, in <module>
    sys.exit(cli())

  File "/usr/local/lib/python3.8/dist-packages/scargo/cli.py", line 307, in gen
    scargo_gen(

  File "/usr/local/lib/python3.8/dist-packages/scargo/commands/gen.py", line 46, in scargo_gen
    if generate_mocks(gen_mock, config.project.target.source_dir, config):

  File "/usr/local/lib/python3.8/dist-packages/scargo/file_generators/mock_gen.py", line 46, in generate_mocks
    header_data = parse_file(src_header)

  File "/usr/local/lib/python3.8/dist-packages/scargo/file_generators/mock_gen.py", line 148, in parse_file
    hdr.namespaces = ParamsExtractor.extract_namespaces(

  File "/usr/local/lib/python3.8/dist-packages/scargo/file_generators/mock_gen.py", line 83, in extract_namespaces
    return [

  File "/usr/local/lib/python3.8/dist-packages/scargo/file_generators/mock_gen.py", line 86, in <listcomp>
    if descendant.kind == CursorKind.NAMESPACE

  File "/usr/local/lib/python3.8/dist-packages/clang/cindex.py", line 1541, in kind
    return CursorKind.from_id(self._kind_id)

  File "/usr/local/lib/python3.8/dist-packages/clang/cindex.py", line 650, in from_id
    raise ValueError('Unknown template argument kind %d' % id)

ValueError: Unknown template argument kind 350

kmc@c59210fddacf:/workspace$
```

**Comment by jze-spyro** [comment]
@kmc-spyro I don't fully understand this error, but it should be fixed by updated dependencies (I had a similar problem before I updated `libclang` to 16.0.0).
I assume you have scargo==1.2.0 installed.
Did you run `scargo update` after updating scargo? It's needed so that the docker image has up-to-date dependencies.
Can you confirm that you have `scargo==1.2.0` and `libclang==16.0.0` inside docker?
