### ISSUE TITLE
ModuleNotFoundError when running scargo commands in esp32 project

### ISSUE THREAD

**Issue by KonradTajstra** [Spyro-Soft/scargo#331]
**Describe the bug**
Python error occurs when trying to run scargo commands in scargo 1.6.4:
```
Traceback (most recent call last):
  File "/usr/local/bin/scargo", line 5, in <module>
    from scargo.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/scargo/cli.py", line 11, in <module>
    from scargo.commands.build import scargo_build
  File "/usr/local/lib/python3.8/dist-packages/scargo/commands/build.py", line 10, in <module>
    from scargo.commands.publish import (
  File "/usr/local/lib/python3.8/dist-packages/scargo/commands/publish.py", line 12, in <module>
    from scargo.config import Config
  File "/usr/local/lib/python3.8/dist-packages/scargo/config.py", line 9, in <module>
    from pydantic import BaseModel, Extra, Field, root_validator
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ModuleNotFoundError: No module named 'typing_extensions'
```

**To Reproduce**
Create new project with esp32 target:
`scargo new test_scargo --target esp32`

Then try running e.g. build inside the project repo:
`scargo build`

This should result in above error

**Expected behavior**

**Additional context**

**Comment by KonradTajstra** [comment]
Fixed in https://github.com/Spyro-Soft/scargo/pull/334
